title: Photography from the Source by Chris Romero
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7728249
  brandStrength: 0.832527450285852
  lightness: 0.6815252
  brandColors:
    - '#050404'
    - '#6FCEFF'
    - '#A4774A'
    - '#FFD8A2'
    - '#FFFF20'
  rhythmicContrast: 0.8007519
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Photography by Chris Romero
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8523093
layout_spectrum: 1
